trigger:
- draft-azure

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: DockerInstaller@0
    #   displayName: Docker install
    #   inputs:
    #     dockerVersion: '17.09.0-ce'
    # - task: CmdLine@2
    #   displayName: Docker build and tag
    #   inputs:
    #     script: |
    #       docker build -t chat-server-draft:$(tag) .
    # - task: CmdLine@2
    #   displayName: Image validation
    #   inputs:
    #     script: |
    #       docker images

    - task: CmdLine@2
      displayName: Get Project Ver.
      inputs:
        - script: |
          cd $(Build.SourcesDirectory)/
          v=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo $v
          echo "##vso[task.setvariable variable=PROJECT_VERSION;]$v"

    # - powershell: |
    #   echo $env:AT | az devops login
    #   az pipelines variable-group variable update --group-id 10 --name WEBSOCKET_CHAT_DEMO_VERSION --value $env:PROJECT_VERSION --org https://dev.azure.com/mitin18 --project “mitin18”
      
    #   displayName: 'Set Global Version'