trigger:
- draft-azure

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: |
    #       $(tag)
    - task: DockerInstaller@0
      displayName: Docker install
      inputs:
        dockerVersion: '17.09.0-ce'

    - task: CmdLine@2
      displayName: Docker build and tag
      inputs:
        script: |
          docker build -t chat-server-draft:$(tag) .

    - task: CmdLine@2
      displayName: Image validation
      inputs:
        script: |
          docker images