trigger:
- draft-azure

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  AT: '$(System.AccessToken)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: DockerInstaller@0
    #   displayName: Docker install
    #   inputs:
    #     dockerVersion: '17.09.0-ce'
    # - task: CmdLine@2
    #   displayName: Docker build and tag
    #   inputs:
    #     script: |
    #       docker build -t chat-server-draft:$(tag) .
    # - task: CmdLine@2
    #   displayName: Image validation
    #   inputs:
    #     script: |
    #       docker images

    # - task: CmdLine@2
    #   displayName: Get Project Ver.
    #   inputs:
    #     script: |
    #       cd $(Build.SourcesDirectory)/
    #       v=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    #       echo $v
    #       echo "##vso[task.setvariable variable=PROJECT_VERSION;]$v"

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          echo $env:AT | az devops login


- stage: PushArtifactst
  displayName: Push Pipeline Artifacts
  jobs:
  - job: PushArtifacts
    displayName: Push Pipeline Artifacts
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Save charts Folder as Artifact'
      inputs:
        PathtoPublish: charts
        ArtifactName: charts
