apiVersion: v1
kind: Service
metadata:
  name: chat-server-draft
spec:
  type: ClusterIP
  selector:
    app: chat-server-draft
  ports:
    - protocol: TCP
      port: 80
      targetPort: chat-server-draft